# Generated by Django 5.1.5 on 2026-01-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbers',
            name='role',
            field=models.CharField(default='barber', max_length=100),
        ),
    ]
