# Generated by Django 5.1.5 on 2026-01-18 11:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0002_barbers_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Barbers',
            new_name='BarbersModel',
        ),
    ]
