# Generated by Django 5.1.5 on 2026-01-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0003_rename_barbers_barbersmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbersmodel',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
