# Generated by Django 5.1.5 on 2026-02-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0004_barbersmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbersmodel',
            name='image',
            field=models.CharField(default='no-image', max_length=100),
        ),
    ]
