# Generated by Django 5.1.5 on 2025-02-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
