# Generated by Django 5.1.5 on 2025-07-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_remove_appointment_person_appointment_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='barber_name',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
