# Generated by Django 5.1.5 on 2025-02-02 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_appointer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_appointer',
        ),
    ]
